apiVersion: apps/v1
kind: Deployment
metadata:
  name: saathi-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saathi-frontend
  template:
    metadata:
      labels:
        app: saathi-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/saathi-491606/saathi-frontend:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: saathi-frontend-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: saathi-frontend
